name: flash_chat
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.2.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.2
  animated_text_kit: ^1.3.0
  firebase_core: ^0.3.4
  firebase_auth: ^0.8.4+4
  cloud_firestore: ^0.9.13+1
  modal_progress_hud: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true



  assets:
  - images/

  fonts:
    - family: SF
      fonts:
        - asset: fonts/SFUIDisplay-Regular.otf
    - family: Raleway_
      fonts :
        - asset: fonts/Raleway-Regular.ttf
